# coding: utf-8

"""
    TextMagic API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@textmagi.biz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.search_chats_response import SearchChatsResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestSearchChatsResponse(unittest.TestCase):
    """SearchChatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchChatsResponse(self):
        """Test SearchChatsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.search_chats_response.SearchChatsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
