# coding: utf-8

"""
    TextMagic API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@textmagi.biz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_invoices_response import GetInvoicesResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetInvoicesResponse(unittest.TestCase):
    """GetInvoicesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInvoicesResponse(self):
        """Test GetInvoicesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_invoices_response.GetInvoicesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
