# coding: utf-8

"""
    TextMagic API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@textmagi.biz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TextMagic
from TextMagic.models.get_user_lists_response import GetUserListsResponse  # noqa: E501
from TextMagic.rest import ApiException


class TestGetUserListsResponse(unittest.TestCase):
    """GetUserListsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUserListsResponse(self):
        """Test GetUserListsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMagic.models.get_user_lists_response.GetUserListsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
