# coding: utf-8

"""
    TextMagic API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MergeSurveyNodesInputObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first_node': 'int',
        'second_node': 'int'
    }

    attribute_map = {
        'first_node': 'firstNode',
        'second_node': 'secondNode'
    }

    def __init__(self, first_node=None, second_node=None):  # noqa: E501
        """MergeSurveyNodesInputObject - a model defined in Swagger"""  # noqa: E501

        self._first_node = None
        self._second_node = None
        self.discriminator = None

        self.first_node = first_node
        self.second_node = second_node

    @property
    def first_node(self):
        """Gets the first_node of this MergeSurveyNodesInputObject.  # noqa: E501

        First node id  # noqa: E501

        :return: The first_node of this MergeSurveyNodesInputObject.  # noqa: E501
        :rtype: int
        """
        return self._first_node

    @first_node.setter
    def first_node(self, first_node):
        """Sets the first_node of this MergeSurveyNodesInputObject.

        First node id  # noqa: E501

        :param first_node: The first_node of this MergeSurveyNodesInputObject.  # noqa: E501
        :type: int
        """

        self._first_node = first_node

    @property
    def second_node(self):
        """Gets the second_node of this MergeSurveyNodesInputObject.  # noqa: E501

        Second node id  # noqa: E501

        :return: The second_node of this MergeSurveyNodesInputObject.  # noqa: E501
        :rtype: int
        """
        return self._second_node

    @second_node.setter
    def second_node(self, second_node):
        """Sets the second_node of this MergeSurveyNodesInputObject.

        Second node id  # noqa: E501

        :param second_node: The second_node of this MergeSurveyNodesInputObject.  # noqa: E501
        :type: int
        """

        self._second_node = second_node

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MergeSurveyNodesInputObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MergeSurveyNodesInputObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
